# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

ame: Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Compile project
        run: mvn clean package -DskipTests --file pom.xml

  rest_tests:
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Execute all REST tests
        run: mvn clean test -Dgroups=api --file pom.xml
      - name: Test Reporter API
        uses: dorny/test-reporter@v1.4.3
        with:
          name: junit execution report api
          path: "**/surefire-reports/TEST-*.xml"
          reporter: java-junit

  soap_tests:
    runs-on: ubuntu-latest
    needs: rest_tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Execute all SOAP tests
        run: mvn clean test -Dgroups=soap --file pom.xml
      - name: Test Reporter UI
        uses: dorny/test-reporter@v1.4.3
        if: always()
        with:
          name: junit execution report ui
          path: "**/surefire-reports/TEST-*.xml"
          reporter: java-junit
